F09
simoncdn/crazee-burger pull request #16
Opened 2023-04-05 21:17 UTC by simoncdn

2023-04-06 16:47 UTC, vileaddev requested changes

2023-04-06 16:47 UTC, vileaddev commented on src/components/pages/order/OrderPage.js
> +    const menuUpdate = menuCopy.map((item) => {
```suggestion
    const menuUpdated = menuCopy.map((item) => {
```

2023-04-06 16:47 UTC, vileaddev commented on src/components/pages/order/OrderPage.js
> +    if (productSelected && productSelected.id === idProductToRemove) {
Pourquoi pas. Ça marche en tout cas. Mais y'avait plus simple. #liveAMA

2023-04-06 16:47 UTC, vileaddev commented on src/components/pages/order/OrderPage.js
> +      if (document.querySelectorAll("input")[1]) {
ouh!!!!!! on ne mélange **jamais** le DOM avec le virtual DOM, jamais jamais jamais 😬 
https://youtu.be/h2a0cSC1Vz8?t=2441

2023-04-06 16:47 UTC, vileaddev commented on src/components/pages/order/OrderPage.js
> +    } else {
éviter les "else" quand c'est possible. Traiter le "else" en edge case, je t'en parlerai en vocal.

2023-04-06 16:47 UTC, vileaddev commented on src/components/pages/order/main/Menu.js
> +          onSelected={isAdminMode ? () => handleProduct(id) : null}
Bien vu, c'était pas précisé dans les règles métier mais tu as raison. Seul l'utilsateur ADMIN devrait avoir le droit de faire ça.

2023-04-06 16:47 UTC, vileaddev commented on src/components/pages/order/main/admin/adminPanel/AdminPanel.js
> +      {currentTabSelected === "edit" && productSelected
à gérer dans tabsConfig

2023-04-06 16:47 UTC, vileaddev commented on src/components/pages/order/main/admin/adminPanel/editForm/EmptyEdit.js
> +    color: #747b91;
design system

2023-04-06 16:47 UTC, vileaddev commented on src/components/pages/order/main/admin/adminPanel/editForm/EmptyEdit.js
> +    color: #747b91;
design system 😒

2023-04-06 16:47 UTC, vileaddev commented on src/components/pages/order/main/admin/tabsConfig.js
> +    Panel: {
Alors ça marche oui mais est-ce que y'a pas plus clair et plus simple ?

2023-04-06 16:47 UTC, vileaddev commented on src/components/reusable-ui/Button.js
> +const selectedStyle = css`
oui ! 💯

2023-04-06 16:47 UTC, vileaddev commented on src/components/reusable-ui/Card.js
> +              onClick={(event) => {
oui mais est-ce qu'il devrait rester en inline dans le JSX ici ?

2023-04-06 16:47 UTC, vileaddev commented on src/components/reusable-ui/Card.js
> +              onClick={(event) => {
en plus y'a un console.log qui traine

2023-04-06 17:25 UTC, simoncdn commented on src/components/pages/order/main/Menu.js
> +          onSelected={isAdminMode ? () => handleProduct(id) : null}
J'ai été obligé de le faire comme ca, sinon quand je cliquais sur un produit alors que je n'étais pas en mode Admin ca me le préselectionner. Du coup quand je passais ensuite en mode admin et que j'ouvrais mon EditPanel le produit était présent

2023-04-06 17:26 UTC, simoncdn commented on src/components/pages/order/main/admin/tabsConfig.js
> +    Panel: {
A la base je les ai avais mis dans un tableau et je joué avec l'index, mais je pense savoir comment je peux simplifier ca :)

2023-04-06 17:29 UTC, simoncdn commented on src/components/pages/order/OrderPage.js
> +      if (document.querySelectorAll("input")[1]) {
Aie je m'y attendais a celui là. Il m'a bien prit la tête, 6h que je suis dessus aujourd'hui j'avais pas réussis a le gérer avec useRef, donc j'ai trouvé cette alternative là. Le but était de livrer une PR fonctionnelle/respectant toute les règles métiers dans l'idée ou je devrais livrer cette feature au client. Et ensuite passer à de la réfacto. Je me doutais que ca allait pas passer a ce niveau là...

2023-04-07 07:40 UTC, vileaddev commented on src/components/pages/order/OrderPage.js
> +      if (document.querySelectorAll("input")[1]) {
> Le but était de livrer une PR fonctionnelle/respectant toute les règles métiers dans l'idée ou je devrais livrer cette feature au client. Et ensuite passer à de la réfacto

Alors dans un contexte réel en entreprise, OUI, là ce que tu as fait c'est parfait ! Prioriser le "make it work" avant le "make it clean" pour livrer au client. Mais dans ce cas, précise en commentaire juste au-dessus de la l.53 : "@TODO: find a better implementation with useRef()" pour qu'on comprenne à la lecture de ta PR que tu étais conscient que ce que tu faisais n'était pas l'idéal 😉

2023-04-07 07:41 UTC, simoncdn commented on src/components/pages/order/OrderPage.js
> +      if (document.querySelectorAll("input")[1]) {
Ah c'est smart !! j'y avais pas pensé top le réflexe !

2023-04-17 22:14 UTC, vileaddev requested changes

2023-04-17 22:14 UTC, vileaddev commented on src/components/pages/order/main/admin/adminPanel/editForm/EditForm.js
> +      <p>
```suggestion
      <span>
```

c'est du texte oui mais qui n'est pas dans un paragraphe.

2023-04-17 22:14 UTC, vileaddev commented on src/components/reusable-ui/Card.js
> +    transition: all 200ms ease-out;
à retirer

2023-04-17 22:14 UTC, vileaddev commented on src/components/pages/order/OrderPage.js
> +    setProductSelected(EMPTY_PRODUCT);
je ne sais pas si cette ligne est utile

2023-04-17 22:14 UTC, vileaddev commented on src/components/pages/order/main/MainRightSide/Admin/AdminPanel/EditForm/InfoEditMessage.js
> +  color: #ffa01b;
design system

2023-04-17 22:14 UTC, vileaddev commented on src/components/pages/order/main/MainRightSide/Admin/AdminTabs.js
> +    focusOnRef(titleEditRef);
si tu mets le await sur chacun d'entre eux, normalement pas besoin de focusOnRef(), tu peux directement faire titleEditRef.current.focus()

2023-04-17 22:14 UTC, vileaddev commented on src/components/pages/order/main/MainRightSide/Admin/AdminTabs.js
> +    focusOnRef(titleEditRef);
pareil ici

2023-04-17 22:14 UTC, vileaddev commented on src/components/pages/order/main/MainRightSide/Menu/Menu.js
> +    focusOnRef(titleEditRef);
pareil ici

2023-04-17 22:14 UTC, vileaddev commented on src/components/pages/order/navbar/NavbarRightSide.js
> +  const displayToastNotification = async () => {
c'était pour quoi déjà celui ci ?

2023-04-17 22:14 UTC, vileaddev commented on src/theme/index.js
> +  primary_halo: "#ff9a23",
yes

2023-04-17 22:14 UTC, vileaddev commented on src/utils/focusOnRef.js
> +export const focusOnRef = (ref) => {
finalement est-ce que c'est utile ? 😕

2023-04-17 23:27 UTC, simoncdna commented on src/components/pages/order/navbar/NavbarRightSide.js
> +  const displayToastNotification = async () => {
To keep the focus on the title input on toggle the admin button

2023-04-17 23:32 UTC, simoncdn commented on src/components/pages/order/OrderPage.js
> +    setProductSelected(EMPTY_PRODUCT);
Elle ne l'ai pas effectivement !

2023-04-18 10:29 UTC, vileaddev approved these changes

2023-04-18 10:30 UTC, merged